version: "3"
services:
  app:
    container_name: appnode
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: dbmongo
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 90:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
 
 